##########################################
#
#  Makefile for Matrix
#
##########################################

TEX=platex 

make: 
	platex field.tex && \
  xdvi field  &

clean:
	rm -f *.aux *.dvi *.log *.bak	
