##########################################
#
#  Makefile for Matrix
#
##########################################

TEX=platex 

make: 
	platex electron2.tex && \
  xdvi electron2  &

clean:
	rm -f *.aux *.dvi *.log *.bak	
