##########################################
#
#  Makefile for Matrix
#
##########################################

TEX=platex 

make: 
	platex product.tex && \
  xdvi product

clean:
	rm -f *.aux *.dvi *.log *.bak	
